### ISSUE TITLE
Unauthenticated user clicking DMARC report link generates error

### ISSUE THREAD

**Issue by sleepycat** [canada-ca/tracker#1392]
Before a user is logged in, clicking the `DMARC report` link generates an error. While the frontend correctly handles the error, we probably don't want to be displaying this link to unauthed users in the first place.

![Screenshot from 2020-12-22 14-58-54](https://user-images.githubusercontent.com/109692/102928169-45015400-4466-11eb-8c22-c176f781313f.png)

It seems like the API might not be handling this missing JWT case as gracefully as it could. 

```json
{
  "errors": [
    {
      "message": "Context creation failed: Invalid token, please request a new one.",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

**Comment by ThomasNickerson** [comment]
Closing as this link has been removed from the navigation bar for users that are not logged in.
