### ISSUE TITLE
Displaying domain detail fails

### ISSUE THREAD

**Issue by sleepycat** [canada-ca/tracker#1687]
![Screenshot from 2021-02-19 18-24-05](https://user-images.githubusercontent.com/109692/108572180-be3eeb00-72df-11eb-8dea-79d9901787db.png)

**Comment by ThomasNickerson** [comment]
Error shown in image is fixed in master, closing. Domain details currently fail to display because of a different breaking change in the API, but fix is in progress and there is a card on the FE project board for it.
