### ISSUE TITLE
Add domain field has "Search for a domain" placeholder text

### ISSUE THREAD

**Issue by sleepycat** [canada-ca/tracker#1688]
![Screenshot from 2021-02-19 18-30-42](https://user-images.githubusercontent.com/109692/108572667-c9464b00-72e0-11eb-88e4-0590cc6f995a.png)

**Comment by ThomasNickerson** [comment]
Not placeholder, but potentially confusing. The intention is that the user searches for a domain already in the Tracker DB and can then choose to add it to their org, rather than allowing the user to freely enter a domain. Closing for now.
