### ISSUE TITLE
Domain Details - Guidance not being translated

### ISSUE THREAD

**Issue by ThomasNickerson** [canada-ca/tracker#1994]
**Describe the bug**
When viewing domain details in French, text on guidance tags remains English.

**To Reproduce**
1. Sign in and go to Domains
2. Click on a domain
3. Switch to French

**Expected behavior**
Guidance tag text should be French when user has selected French

**Screenshots**
![image](https://user-images.githubusercontent.com/64759920/112858012-d72d7f80-9087-11eb-90f1-8d9aba6a1e39.png)
![image](https://user-images.githubusercontent.com/64759920/112858207-05ab5a80-9088-11eb-9a51-3524b6a977b4.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome
 - Version 89.0.4389.90

**Additional context**
Note that some of the text in the no guidance tags found message (bottom of second image) is being translated properly.

**Comment by AdamPrins** [comment]
added in  #2712
