### ISSUE TITLE
Page Size selector does not change page size

### ISSUE THREAD

**Issue by michaeldavie-cyber** [canada-ca/tracker#2015]
**Describe the bug**
On https://tracker.alpha.canada.ca/dmarc-summaries, the Page Size selector does not always change the page size.

**To Reproduce**
1. Go to https://tracker.alpha.canada.ca/dmarc-summaries
2. Click on Page Size, choose 100.
3. Page size does not change

**Expected behavior**
Page size should refresh to the selected size.

**Screenshots**
![image](https://user-images.githubusercontent.com/60613685/113204866-924a4a00-923b-11eb-88f2-cd484fd8c1b9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 78.8.0esr (64-bit)

**Additional context**
![image](https://user-images.githubusercontent.com/60613685/113204999-c160bb80-923b-11eb-8002-2be18ddb3faf.png)

**Comment by ThomasNickerson** [comment]
Resolved by #2042 - `usePaginatedCollection.js` was hardcoded to pull 10 entries per page prior to that PR, now it respects the `recordsPerPage` value passed to it, which fixes this issue.
