### ISSUE TITLE
Missing DKIM records show as pass

### ISSUE THREAD

**Issue by michaeldavie-cyber** [canada-ca/tracker#2016]
**Is your feature request related to a problem? Please describe.**
This domain has no DKIM record data, but shows as "pass".
![image](https://user-images.githubusercontent.com/60613685/113206395-67f98c00-923d-11eb-929b-07a0636bc618.png)

**Describe the solution you'd like**
Domains with no DKIM data should show as "neutral" or "unknown".

**Describe alternatives you've considered**
Unlike SPF and DMARC, domains that are not used for mail do not require DKIM records. By evaluating a domain's SPF record, we could determine whether any IP addresses have been authorized to send mail. If any have, the domain should have a DKIM record and the appropriate result would be "fail" if one is missing.

**Comment by ThomasNickerson** [comment]
Main issue is closed by #2519, but will add the alternative solution to scanner project board for future consideration
