### ISSUE TITLE
/domains/<somedomain>/dmarc-report/LAST30DAYS/2021 makes many requests

### ISSUE THREAD

**Issue by sleepycat** [canada-ca/tracker#2026]
The dmarc-report page makes 8 separate requests to the API to fetch the data for the page.

**To Reproduce**
Visit `/domains/<somedomain>/dmarc-report/LAST30DAYS/2021`
Check out the network tab in the dev tools 

![Screenshot from 2021-04-01 11-27-27](https://user-images.githubusercontent.com/109692/113318179-31c01900-92de-11eb-9eda-43aa9fb246ac.png)

**Expected behavior**
GraphQL queries should be combined into a smaller number of requests, ideally 1.

**Comment by AdamPrins** [comment]
Looking into this, three of them are duplicate calls (*)
Possibly related to #2503?

DmarcReportGraph
PaginatedDkimFailureReport
PaginatedDmarcFailureReport
PaginatedSpfFailureReport
PaginatedFullPassReport
*PaginatedSpfFailureReport
*PaginatedDmarcFailureReport
*PaginatedDkimFailureReport
