### ISSUE TITLE
Icon usage error android-chrome-192x192.png

### ISSUE THREAD

**Issue by sleepycat** [canada-ca/tracker#2040]
When loading the site, an error message is printed in the console when using Chromium (not on Firefox though):
![Screenshot from 2021-04-06 11-20-58](https://user-images.githubusercontent.com/109692/113735437-40397680-96ca-11eb-95af-f21360ca5495.png)

**Desktop:**
 - OS: Manjaro Linux
 - Browser: Chromium
 - Version 89

**Comment by ThomasNickerson** [comment]
On Windows I was able to reproduce in Edge version 89.0.774.68 but could not reproduce in Chrome version 89.0.4389.114, even in incognito after clearing cache and cookies. Comparing network tabs, Chrome doesn't seem to request the resource in question while Edge does. Will investigate further.
