### ISSUE TITLE
Ability to Add and Edit DKIM Selectors

### ISSUE THREAD

**Issue by nsdeschenes** [canada-ca/tracker#2054]
**Is your feature request related to a problem? Please describe.**
Currently we are only able to create a domain, and edit the domain we previously submitted, without the ability to add and edit their respective DKIM selectors.  

**Describe the solution you'd like**
What I'm thinking of is something similar to the edit domain popup that occurs when editing a domain, with "dynamic"  text boxes (button to increase the amount of boxes with a label like "Add Selector"). For reference, DKIM selectors are taking in as an array of strings in the API (example below).

`createDomain` Example:
```graphql
mutation {
  createDomain(
    input: { domain: "new-domain", selectors: ["selector1", "selector2"] }
  ) {
    result {
      ... on Domain {
        domain
        selectors
      }
    }
  }
}
```
---
`updateDomain` Example:
```graphql
mutation {
  updateDomain(
    input: { domainId: "domainId", selectors: ["selector1", "selector2"] }
  ) {
    result {
      ... on Domain {
        domain
        selectors
      }
    }
  }
}
```

**Comment by ThomasNickerson** [comment]
Closed by #2455
