### ISSUE TITLE
Make DMARC guidance tags human-readable

### ISSUE THREAD

**Issue by michaeldavie-cyber** [canada-ca/tracker#2060]
**Is your feature request related to a problem? Please describe.**
On the DMARC Report page, the text values in the Guidance columns of the SPF Failures by IP Address and DKIM Failures by IP Address tables are not useful.

**Describe the solution you'd like**
We should make the in-table text more useful (e.g. agg-dkim-unsigned --> No DKIM signature), potentially with a pop-out containing further information or a link to the guidance.

**Additional context**
![image](https://user-images.githubusercontent.com/60613685/114029805-e363ca80-9847-11eb-830f-55c96e3cb131.png)

**Comment by nsdeschenes** [comment]
So this is actually a multi-tiered issue, we need to update the core service to pull the tags into the db, need to create loaders etc in the API, and then we can get the frontend up to par.

**Comment by nsdeschenes** [comment]
@lcampbell2 So the API has had this updated, and there is a `guidanceTag` field that returns the same structure as the guidance tags for the other scans we perform, however it is only a single guidance tag, not a list.
