### ISSUE TITLE
Admin interface lacks means of deleting users

### ISSUE THREAD

**Issue by sleepycat** [canada-ca/tracker#2163]
The admin page allows adding users to organizations, but does not include a means of removing them.
![Screenshot from 2021-04-30 12-27-45](https://user-images.githubusercontent.com/109692/116725314-c5553a00-a9af-11eb-8cfe-ceb58db3845d.png)

It's not clear that the API provides an means of deleting a user.

**Comment by nsdeschenes** [comment]
API wise, this can be completed using the following mutation:
```graphql
mutation {
  removeUserFromOrg (input: {
    userId: ""
    orgId: ""
  }) {
    result {
      ... on RemoveUserFromOrgResult {
        status
      }
      ... on AffiliationError {
        code
        description
      }
    }
  }
}
```
