### ISSUE TITLE
Slow database queries

### ISSUE THREAD

**Issue by sleepycat** [canada-ca/tracker#2228]
ArangoDB is surfacing some slow queries in the database UI.

![Screenshot from 2021-05-14 11-55-06](https://user-images.githubusercontent.com/109692/118297362-0703db80-b4ac-11eb-8a43-3d5ef30c59e4.png)

**Comment by ThomasNickerson** [comment]
![image](https://user-images.githubusercontent.com/64759920/124470681-4e06a280-dd72-11eb-95ec-a11a87f99eed.png)
Closed by #2574 and #2551
