### ISSUE TITLE
Cancel Old Requests When Searching

### ISSUE THREAD

**Issue by nsdeschenes** [canada-ca/tracker#2311]
**Describe the bug**
When users are searching for domains, orgs, etc. every character they enter a new request is sent without the old one being cancelled.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Domains'
2. Click on the search box
3. Open up browser network tools
4. Enter characters for searching
5. Watch network tools and requests will be made for each character

**Expected behavior**
When new characters are added to the search string the older requests should be cancelled. Here are some issues threads from Apollo Client.
- [Feature idea: Abort pending requests #40](https://github.com/apollographql/apollo-feature-requests/issues/40)
- [if a Query is stopped using AbortController, it cannot be executed again. #4150](https://github.com/apollographql/apollo-client/issues/4150)

**Screenshots**
![](https://user-images.githubusercontent.com/7891920/120177006-4b96b300-c1de-11eb-884f-459478a82092.png)

**Desktop:**
 - OS: Ubuntu 20.04
 - Browser: Brave
 - Version: 91.1.25.68

**Comment by AdamPrins** [comment]
Possibly able to close since debouncing has been added in #2300 #2339. 
Searches are only performed when the user stops typing (500ms since last change).
