### ISSUE TITLE
Organization pages break when using french

### ISSUE THREAD

**Issue by FestiveKyle** [canada-ca/tracker#2323]
When on an organization summary page ( /organizations/org-slug ), page breaks when switching language.

```
{
    errors: [
      {
        message: 'todo',
        locations: [
          {
            line: 2,
            column: 3,
          },
        ],
        path: ['organization'],
        extensions: {
          code: 'INTERNAL_SERVER_ERROR',
        },
      },
    ],

    data: {
      organization: null,
    },
}
```

**Comment by AdamPrins** [comment]
I'm not seeing any errors on language switching languages, is this still occurring, or can it be closed?

<img width="1101" alt="Screen Shot 2021-06-23 at 10 06 03 AM" src="https://user-images.githubusercontent.com/55841241/123111188-b7012880-d40a-11eb-8901-e4c4ff367eb5.png">

**Comment by FestiveKyle** [comment]
Seems to be good!
