### ISSUE TITLE
Missing error message for auth failure on subscriptions

### ISSUE THREAD

**Issue by ThomasNickerson** [canada-ca/tracker#2412]
**Describe the bug**
When attempting a subscription with an invalid auth token, the error message reads only "todo".

**To Reproduce**
1. Go to https://tracker.alpha.canada.ca/graphql
2. Attempt to start any subscription without logging in
3. See error

**Expected behavior**
The error message returned should be similar to the one returned by attempting other operations with an invalid token.

**Comment by nsdeschenes** [comment]
I have attempted to recreate this issue, however I believe it's just translation related, may need to check your language settings in your browser.

![Screenshot from 2021-06-11 06-47-44](https://user-images.githubusercontent.com/7891920/121667708-f2057280-ca80-11eb-8e60-38dbe8a016d5.png)
