### ISSUE TITLE
UserList.test.js has flakey results

### ISSUE THREAD

**Issue by lcampbell2** [canada-ca/tracker#2429]
**Describe the bug**
UserList.test.js failed on first cloudbuild, but passed on a subsequent build

**To Reproduce**
1. run `npm test` OR `npm test src/\_\_tests\_\_/UserList.test.js`
2. Has chance of passing or failing

**Expected behavior**
This test should pass every time

**Screenshots**
![Screenshot from 2021-06-11 13-20-54](https://user-images.githubusercontent.com/64781228/121727072-cb1b6080-cac1-11eb-8609-9609b9515765.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Comment by FestiveKyle** [comment]
Fixed by #2438
