### ISSUE TITLE
Duplicate graphql calls for OrgDetails

### ISSUE THREAD

**Issue by AdamPrins** [canada-ca/tracker#2503]
**Describe the bug**
The 'OrgDetails' graphql is being called twice when loading an organization. 

**Expected behavior**
There should only be one graphql call for 'OrgDetails'

**Screenshots**
<img width="1121" alt="Screen Shot 2021-06-23 at 11 25 22 AM" src="https://user-images.githubusercontent.com/55841241/123126194-2d0b8c80-d417-11eb-8e46-7197b180105a.png">
<img width="1121" alt="Screen Shot 2021-06-23 at 11 25 10 AM" src="https://user-images.githubusercontent.com/55841241/123126174-2aa93280-d417-11eb-8df6-00eed9529b3b.png">

**Comment by AdamPrins** [comment]
The duplicate call is somehow linked to OrganizationAffiliations. Removing it means the duplicate call isn't run.
Specifically it is caused by the usePaginatedCollection function.

In the image, you can see that only the first OrgDetails is called, and the domains query are run.
The Affiliations query was commented out, and that caused the second OrgDetails not to be called
<img width="1061" alt="Screen Shot 2021-06-24 at 10 32 23 AM" src="https://user-images.githubusercontent.com/55841241/123281393-a8cd0e00-d4d7-11eb-890f-656b8610abd0.png">

**Comment by FestiveKyle** [comment]
This seems to be fixed now. I think the cache policy change from this PR fixed it:
https://github.com/canada-ca/tracker/pull/2707/files#diff-4f4840bf27838c522c31c6e414dc630a580a9e763bfbf82b1d04ed1c8cd0f5bcR22-L25
