### ISSUE TITLE
Organisations are not clickable at small screen sizes.

### ISSUE THREAD

**Issue by sleepycat** [canada-ca/tracker#2688]
![orgs-not-clickable](https://user-images.githubusercontent.com/109692/126697937-75349ffb-7771-4cf6-97c3-59f192429b54.gif)

**Comment by FestiveKyle** [comment]
This is weird. `master` has the changes for the "View Details" button on org cards. Works locally. From PR #2657.

https://github.com/canada-ca/tracker/blob/master/frontend/src/OrganizationCard.js#L126-L138

![image](https://user-images.githubusercontent.com/47400288/126700615-651d3f58-4d5e-499a-ace8-037ef0d4e4b7.png)

**Comment by AdamPrins** [comment]
Is there a chance that the minification of the code means that this will never be true?
``` cardType?.displayName  === 'Flex'```

Since I am seeing it work on the local host, but not on master.
