### ISSUE TITLE
Users can't view their orgs

### ISSUE THREAD

**Issue by sleepycat** [canada-ca/tracker#2689]
Trying to view an organisation as a regular user throws an error complaining that it `Cannot read property 'organization' of undefined`.
The reason for the undefined object appears to be the API responding with: `Cannot query affiliations on organization without admin permission or higher.`
![regular-users-break-orgs](https://user-images.githubusercontent.com/109692/126698648-e725008c-b040-4300-8ba7-e6c0ae66ef9a.gif)

**Comment by nsdeschenes** [comment]
@sleepycat this is a FE query issue, users are unable to query the affiliation field so the query on the front end needs to be updated if the user is not an admin.

**Comment by AdamPrins** [comment]
This is due to the org details query pulling the affiliation list, as I talked about in #2518

We need to update the query on the front end, but also extract the total affiliations to the org itself in the api
