### ISSUE TITLE
Scan UI spins forever when scanners timeout

### ISSUE THREAD

**Issue by sleepycat** [canada-ca/tracker#2727]
Launching a user initiated scan, sometimes the scanner times out, the result is that the frontend spins forever.
![cds-spinning](https://user-images.githubusercontent.com/109692/127349484-f611ffd4-11e1-4720-8c1b-fd19e8113844.gif)

**Comment by nsdeschenes** [comment]
@ThomasNickerson and @FestiveKyle I'm thinking we could probably use the checkpoint system that we introduced to help and solve this issue.
