### ISSUE TITLE
HTTPS-everywhere vs Tracker bakeoff

### ISSUE THREAD

**Issue by sleepycat** [canada-ca/tracker#2751]
We need to revisit the [analysis that was done previously](https://github.com/canada-ca/tracker/wiki/Comparing-Results-from-Tracker-1.0-and-Tracker-2.0) now that we have all the domains from HTTPS-everywhere in Tracker.

I'd be important to emphasis definitions, and where they differ, as well as having a diff per domain.

The goal is to equip the folks around the Tracker project to explain the scores/differences clearly when departments ask. 

For context, these are the categories HTTPS-everywhere is displaying to the users, and so our explanations will need to account for that.

![https-everywhere-categories](https://user-images.githubusercontent.com/109692/127702021-3b3aa117-3ce8-432c-b667-e3e2b1ce1fdd.png)

**Comment by h701h** [comment]
https-everywhere is in the process of being sunset.
