### ISSUE TITLE
Updating Knative services leaves behind old deployments

### ISSUE THREAD

**Issue by ThomasNickerson** [canada-ca/tracker#2764]
**Describe the bug**
When a change is made in master that requires Flux to update an image for one of our serverless microservices, it creates a new numbered deployment, leaving behind the previous one with 0 pods. Attempting to delete these zombie deployments, at least on the GKE dashboard, has no effect.

**To Reproduce**
1. Merge a change that will result in a new image being built for one of the queues or scanners
2. Wait a little for CD to happen, then check the GKE workloads tab.

**Expected behavior**
Once the new deployment has availability, the old deployment should be removed. At the very least it should be possible to delete them.

**Screenshots**
![image](https://user-images.githubusercontent.com/64759920/128030010-e0748525-8568-40f1-b4b0-cf817ca6f1af.png)

**Additional context**
It might be helpful to see if the behaviour is the same on our Azure deployments, but I don't have access to them.

**Comment by sleepycat** [comment]
Solved by removing knative!
