### ISSUE TITLE
KNative proxy timing out while attempting to connect to HTTPS scanner container

### ISSUE THREAD

**Issue by ThomasNickerson** [canada-ca/tracker#2797]
**Describe the bug**
Tracker's HTTPS scanner pods occasionally become unready due to the KNative proxy container timing out while attempting to connect to the scanner container. They become stuck in a loop of timing out and retrying and the deployment must be deleted to allow Flux to recreate it and resolve the issue. No scans are performed by the pod while in this state.

**To Reproduce**
Issue is intermittent and cause is unknown

**Expected behavior**
Pods should remain ready, and be automatically restarted if unready.

**Screenshots**
![image](https://user-images.githubusercontent.com/64759920/128550160-81c73e75-cde8-4eb4-a110-90e464060672.png)
![image](https://user-images.githubusercontent.com/64759920/128550283-d61b7324-5f09-4a80-8d96-5d1ea283f7cb.png)

**Additional context**
There are some log messages that suggest this may be caused by failure to properly close connections, but this needs to be investigated further:

```
[2021-08-05 16:21:22 +0000] [6940] [INFO] Error while closing socket [Errno 9] Bad file descriptor

[2021-08-05 16:21:29 +0000] [6940] [INFO] Waiting for connections to close. (CTRL+C to force quit)
```

**Comment by sleepycat** [comment]
Solved via the removal of knative.
