### ISSUE TITLE
Update Notify With 60 min expiary

### ISSUE THREAD

**Issue by AdamPrins** [canada-ca/tracker#2812]
These four notifications need to be updated to 60 min from 24 hours on notify

- [User Password Reset (EN) - Email](https://github.com/canada-ca/tracker/wiki/Notification-Integration#user-password-reset-en---email)
- [User Password Reset (FR) - Email](https://github.com/canada-ca/tracker/wiki/Notification-Integration#user-password-reset-fr---email)
- [Verification Email (EN) - Email](https://github.com/canada-ca/tracker/wiki/Notification-Integration#verification-email-en---email)
- [Verification Email (FR) - Email](https://github.com/canada-ca/tracker/wiki/Notification-Integration#verification-email-fr---email)

`Please note the above link will be valid for the next 60 minutes.`
`Veuillez noter que le lien ci-dessus n’est valable que pour les prochaines 60 minutes.`

**Comment by nsdeschenes** [comment]
Just updated the links adding in an extra `-`.

**Comment by nsdeschenes** [comment]
Completed this in notification should be all good to go now!
