### ISSUE TITLE
Some curves being incorrectly classified as weak

### ISSUE THREAD

**Issue by ThomasNickerson** [canada-ca/tracker#2838]
**Describe the bug**
In the SSL results for domains, the `prime256v1` curve (and potentially others) incorrectly appears under "Weak Curves" despite being recommended by CCCS in [ITSP 40.062](https://cyber.gc.ca/en/#tab4). The confusion occurs because categorization of supported curves is done by comparing the values [SSLyze](https://nabla-c0d3.github.io/sslyze/documentation/index.html) returns to the [JSON version](https://github.com/CybercentreCanada/ITSP.40.062/blob/7b5f867c554eee59d70e5347e46be51a750bce28/transport-layer-security/tls-guidance.json#L57-L81) of the CCCS recommended curve table; while CCCS consistently uses the [SECG](https://www.secg.org/) curve names, SSLyze uses ["[t]he ANSI X9.62 name if available, otherwise the SECG name"](https://nabla-c0d3.github.io/sslyze/documentation/available-scan-commands.html#id18). In this case the ANSI name `prime256v1` is equivalent to `secp256r1`. Curves for which there exists an ANSI name are likely to be incorrectly classified.

**Expected behavior**
Curves should be categorized in a way that is consistent with CCCS guidance, and they should be displayed using SECG names for consistency as well.

**Screenshots**
![image](https://user-images.githubusercontent.com/64759920/129597776-6d0fe2b9-46af-43f1-861f-84b90062dca8.png)

**Additional context**
See [RFC4492 Appendix A](https://datatracker.ietf.org/doc/html/rfc4492#appendix-A) for curve name equivalencies.

If we continue to rely on SSLyze it might make sense to open an issue about curve names on their [github](https://github.com/nabla-c0d3/sslyze), as using multiple naming schemes seems like a poor design choice.

**Comment by CADbryon** [comment]
Scanner naming conventions are askew.
