### ISSUE TITLE
Summary donut on landing page should align with Tracker 1.0 Summary

### ISSUE THREAD

**Issue by ptd-tbs** [canada-ca/tracker#3153]
The summary donut on the landing page for Tracker 2.0 should display "Domains that enforce HTTPS." Specifically, it should present item 6.1.1 ("is configured for HTTPS (and redirected from HTTP)."

**Comment by FestiveKyle** [comment]
The field for this check can be found in an htts scan document's "enforced" property. If "enforced" is "Strict", the domain either strictly enforces and defaults to HTTPS, or immediately redirects to HTTPS ([logic here](https://github.com/canada-ca/tracker/blob/master/scanners/https-scanner/tls.py#L32-L75)).

We can create a new summary object in [summaries.py](https://github.com/canada-ca/tracker/blob/master/services/summaries/summaries.py) for the [landing page summary](https://github.com/canada-ca/tracker/blob/4b14b10038ff75f8568198b50edd3ca9f35173d2/services/summaries/summaries.py#L148-L196) and [individual organization summaries](https://github.com/canada-ca/tracker/blob/4b14b10038ff75f8568198b50edd3ca9f35173d2/services/summaries/summaries.py#L199-L286). New queries will also have to be added to the API to give users access to this data ([landing page summaries](https://github.com/canada-ca/tracker/tree/master/api/src/summaries/queries), [organization summaries](https://github.com/canada-ca/tracker/blob/master/api/src/organization/objects/organization-summary.js)).

**Comment by CADbryon** [comment]
Effort of 1 day.  
Majority of the functionality is already in place.
