### ISSUE TITLE
Istio sidecar injection for Kube-ArangoDB

### ISSUE THREAD

**Issue by sleepycat** [canada-ca/tracker#3168]
Initially, we had enabled sidecar injection for the DB namespace, but this resulted in weird errors when querying the database. We resolve the issue by disabling the sidecar injection, trading observability for working queries.
It turned out that the Kube-ArangoDB operator didn't get along well with Istio, but this was something the developers planned to resolve in an upcoming release.
This issue is a reminder to explore sidecar injection again.

**Comment by h701h** [comment]
Placing in progress as the label suggests. I think this item needs another update on its state.

**Comment by h701h** [comment]
Side cars may not work well with our internal service providers infra. Closing until needed.
