### ISSUE TITLE
Add "last scanned" date back in UI

### ISSUE THREAD

**Issue by sleepycat** [canada-ca/tracker#3170]
#In conjunction with Scanner work.

Previously the date of the last scan was displayed in the UI. This was removed a while ago to save space.
Unfortunately without this important sign-of-life, it's difficult to tell how reliable of the rest of the information is, or if Tracker is working at all.
Something like a "last scanner" date should be added back in the UI.
![Screenshot from 2021-07-30 15-26-48](https://user-images.githubusercontent.com/109692/140803192-74c258b1-b2f0-4baa-9c4c-ae6d128fe1ff.png)

- [ ] Merge into #3667

**Comment by lcampbell2** [comment]
New plan: keep removed from card level for now, move into guidance page for detached scanners (last scanned for web, dns, vulns, etc.)
