### ISSUE TITLE
Pass tracing headers when querying the database

### ISSUE THREAD

**Issue by sleepycat** [canada-ca/tracker#3172]
Way back in 6b253388fc86b we added [middleware](https://www.npmjs.com/package/arango-express) that would configure the arangodb client so that it properly passes tracing headers like `X-Cloud-Trace-Context` on to the database so that requests can be traced end-to-end.
That middleware attaches the query object directly to the incoming request, and the API should be adjusted to use that query object rather than the one in the context.

**Comment by CADbryon** [comment]
- [ ] Review ISTIO w/DB
- [ ] If successful, this issue could be a non-issue
