### ISSUE TITLE
Merge flux config into appropriate app overlay

### ISSUE THREAD

**Issue by sleepycat** [canada-ca/tracker#3176]
Right now our k8s config is spread across three folders: `/app`, `/platform` and `/deploy`. While the separation between app and platform has been sensible, keeping the flux related config in the `/deploy` folder has been a frequently fired [footgun](https://www.urbandictionary.com/define.php?term=footgun).
The contents of the `/deploy` folder should be folded into an appropriate folder in app.

**Comment by h701h** [comment]
Being added to new folder/cluster.
