### ISSUE TITLE
Add disclaimer to the Tracker's main page.

### ISSUE THREAD

**Issue by CADbryon** [canada-ca/tracker#3201]
A disclaimer must be added to the Tracker main page to advise that results will be different across HTTPS Everywhere and Tracker.
(UX)

**Comment by IamRahim** [comment]
@greggoryelton - you were going to do a quick compare at the org - domain level - to verify that if a department does a compare, they will see similar results. If that has been done and all is good, we don't necessarily need the disclaimer on the page.
