### ISSUE TITLE
Update Login Requirements

### ISSUE THREAD

**Issue by CADbryon** [canada-ca/tracker#3203]
Update:  Only Administrators who are responsible for an organization's domains will be required to authenticate into Tracker.  All other 'users' will have read-only privileges to all information as long the tool is accessed from within the GC environment.

Review and establish the various roles and access within Tracker.

- Super Admin (TBS)
- Admin (Client users)
- User (Reporting)

> Rahim and Po discussion:
> 
>     * Anyone can go to the site and see everything.
> 
>     * Admins responsible for domain lists for an organization will need to be authorized.

We'll try to implement this with the following steps:

 - [x] #3376
 - [x] #3377

**Comment by CADbryon** [comment]
@CADbryon to follow up with Caitlin.

**Comment by CADbryon** [comment]
Direction required regarding MAF indicators. @CADbryon

**Comment by CADbryon** [comment]
Next meeting set for Dec 8.

**Comment by CADbryon** [comment]
Work on messaging.  Using Caitlin's template.

**Comment by CADbryon** [comment]
Rahim and Po discussion:  
- Anyone can go to the site and see everything.  
- Admins responsible for domain lists for an organization will need to be authorized.

**Comment by FestiveKyle** [comment]
> Rahim and Po discussion:
> 
>     * Anyone can go to the site and see everything.
> 
>     * Admins responsible for domain lists for an organization will need to be authorized.

We'll try to implement this with the following steps:

 - [ ] Create API query to check if login is required for domains/orgs/dmarc report queries
 - [ ] Adjust frontend to use the above query to conditionally render pages for domains/orgs/dmarc reports
