### ISSUE TITLE
Create communication to users/testers for Dec 1

### ISSUE THREAD

**Issue by CADbryon** [canada-ca/tracker#3218]
Information must be provided to users for our Dec 1 milestone.

- [x] Invitation letter
- [x] Contact information
- [x] Requesting feedback
- [x] What to test (do we want to focus on anything specific?)
- [x] Where/how to provide feedback

**Comment by CADbryon** [comment]
Hi, @greggoryelton, can we have an update on the Invitation Template?

**Comment by greggoryelton** [comment]
@CADbryon Invitation template email is almost complete. Setting up avenues for feedback once the user is done.

**Comment by greggoryelton** [comment]
@CADbryon Email invitation has been sent.
