### ISSUE TITLE
Tracker Staging - Allow Other GC Depts. Access

### ISSUE THREAD

**Issue by CADbryon** [canada-ca/tracker#3243]
Users from departments outside of TBS are receiving a 504 timeout when trying to connect to staging.tracker.canada.ca.

Faltacas, Vasilios added a comment - 2 hours ago
According to the Appscan report there are few things that would need to be addressed.  While the items are listed as low in the report, the items in question are counter to some of the ITPINs that are in place with regards to HTTPS implementations:

1.  Support for TLS 1.0 and 1.1 is enabled

2.  There are a few SHA-1 cipher suites that are supported

**Comment by greggoryelton** [comment]
Bruce gave some insight into the issue. 
1. TLS 1.0 and TLS 1.1 have been disabled
2. SHA Ciphers were accepted to give access to depts. that use older browsers. 

This is not on the application level, instead on the infrastructure/fw side

**Comment by CADbryon** [comment]
Take snapshot of DB.
Give access to Prod for IMTD.

**Comment by CADbryon** [comment]
Rescaned.  
Test users are now in Prod.
