### ISSUE TITLE
Upgrade from Istio-on-GKE to ASM

### ISSUE THREAD

**Issue by CADbryon** [canada-ca/tracker#3266]
We are currently using a beta version, Istio on Google Kubernetes Engine (GKE), and this service will graduate to a GA version, ASM. It is recommended that TBS upgrade from Istio-on-GKE to ASM before the support is discontinued.

Based on the following, we have three options that we suggest and would like to talk to you about:

1. Start migrating over to ASM following this guide 

2. Wait for CCCS approval (submitted ASM to CCCS during the last refresh cycle so it should be soon) of ASM then migrate. Istio-on-GKE will stop being supported in Q2 2021.

3. If neither of those options is possible they can continue to use OSS Istio if that is preferred. **(Recommended)**

**Comment by sleepycat** [comment]
This is resolved. We are't using Istio-on-GKE, so no action is needed. 
For the moment we're running Istio ourselves which keeps things very consistent across GKE and AKS.
