### ISSUE TITLE
Investigate DMARC Summaries Page.

### ISSUE THREAD

**Issue by CADbryon** [canada-ca/tracker#3332]

**Comment by CADbryon** [comment]
Kyle to investigate today.
Plan B. check with JF at CCCS to see if the issue is on their side.

**Comment by CADbryon** [comment]
Incorrect connections to the API.
 - need to 'claim' organizations to domains.
 - What is the 'single source of truth' for our domain list?

**Comment by FestiveKyle** [comment]
We were using an incorrect azure connection string - updated to new string and the DMARC summaries are now available on production
