### ISSUE TITLE
Search for and suggest DKIM selectors (rework how to add selectors)

### ISSUE THREAD

**Issue by FestiveKyle** [canada-ca/tracker#3511]
First 

- [x] Contact the trusted provider to see if/when they can send ALL the trusted selectors  + per domain
- [x] B Stream?
- [ ] Testing strategy
- [ ] Marketing
  - [ ] Deal with the current manual dkims 

Second
- [x] Change DKIM to read-only (why? 30k clicks is never going to happen)
- [x] Work with the trusted provider to get all the selectors
- [x] Set DKIM to positive ONLY when its imported from trusted provider (push an message ppl to do this right)
- [ ] When a new domain is added give the user info on how to get DKIM approved as compliant (give instruction on web site, send some emails that they can forward to others)
  - [ ] Provide advice on how to clean up dead selectors 
  - [x] 
- [ ] Create new test issues for backlog
 

When going A stream (trusted provider results are all in)
- [ ] Broadcast new feature and the new numbers to SecureGCDigital.  Include instructions on how to be on the trusted provider list.

Third (will be its own ticket later)
- [ ] Create scanner/parser for parked domains (IF p= GOOD, else BAD)
- [ ] Create scanner/parser for domains that are properly setup to not send email (IF p= GOOD, else BAD). 
- [ ] Work with DNS team and the email management team to set better defaults. Also make change requests to email group because Tracker team knows they are not compliant.  
- [ ] Create new issue to test like the UK tests (is this even possible for us?)
- [ ] If DKIM selector is older than 1 year, remove it. 
  - [ ] Create instructions why. 

~Besides deciding how these changes should be manually completed, we could search for and suggest selectors to be added to domains in Tracker. Microsoft/M365 uses "selector1" and "selector2" for their selectors.~

~Also consider: use "info" status for domains without DKIM selectors.~

- [ ] ~When we move this testing to prod can we do it with only select orgs [TBS, ?]~
- [ ] ~Add super trust worthy selectors by default~
- [ ] ~Found selectors have to be added by Org Admins~
- [ ] ~Find all on first run. ~
- [ ] ~Search every 30 days~
- [ ] ~Create a blocklist so users can dismiss found selectors and remove selectors which might be found in DMARC summaries~

**Comment by CADbryon** [comment]
`Dig` the domain key subdirectory to see if it exists.

**Comment by h701h** [comment]
![Image](https://github.com/canada-ca/tracker/assets/74711155/8628df62-b0bc-4a8a-8e99-18d9cab90513)

**Comment by h701h** [comment]
Merged into https://github.com/orgs/canada-ca/projects/1/views/1?filterQuery=dkim&pane=issue&itemId=46489989
