### ISSUE TITLE
"Sort by ITPIN" shows mix of pass/fail

### ISSUE THREAD

**Issue by sleepycat** [canada-ca/tracker#3563]
Sorting by ITPIN does not sort correctly. Records are shown that both pass and fail.

**To Reproduce**
1. Go to the domains page
2. search for "canada.ca"
3. Select "sort by" and "ITPIN" 
4. Scroll to see ITPIN status of returned results.

**Expected behavior**
ITPIN status should be all pass or all fail depending on sort order. Instead results are mixed:
![Screenshot from 2022-03-28 12-06-20](https://user-images.githubusercontent.com/109692/160440497-84972b1c-085e-462e-b01d-a90f9ea865bd.png)

**Comment by lcampbell2** [comment]
Value being computed in API instead of taken from database. 
@FestiveKyle to include computation in processor to simplify.
@lcampbell2 to implement API changes

**Comment by h701h** [comment]
Closing this issue as ITPIN is not an sort option and we are removing the ITPIN section from this view.
