### ISSUE TITLE
Run Istio with multiple ingresses

### ISSUE THREAD

**Issue by sleepycat** [canada-ca/tracker#3623]
This is needed to [support  zero downtime deployments](https://www.canada.ca/en/government/system/digital-government/policies-standards/government-canada-enterprise-architecture-framework.html#:~:text=support%20zero%E2%80%91downtime%20deployments).
This was working previously but currently we're only running a single ingress gateway for some reason, meaning changes to Istio cause a short period of downtime (typically a few seconds).

**Comment by CADbryon** [comment]
@sleepycat, Any updates for this ticket?

**Comment by h701h** [comment]
@sleepycat Does this change require any of the network diagrams, in our security documentation, to be updated?
