### ISSUE TITLE
Redirect HTTPS Everywhere to Tracker (from Rahim)

### ISSUE THREAD

**Issue by h701h** [canada-ca/tracker#3671]
•	English: https://https-everywhere.canada.ca/en/index/ --> https://tracker.canada.ca/
•	French: https://https-partout.canada.ca/fr/index/  https://tracker.canada.ca/

- [x] reach out to David Rossi to find out who would be able to address it from the https-everywhere side

Jira ticket:
https://jira.tbs-sct.gc.ca/browse/AZ-12914

**Comment by FestiveKyle** [comment]
Both redirects working as expected.
