### ISSUE TITLE
Regen DMARC reports

### ISSUE THREAD

**Issue by h701h** [canada-ca/tracker#3713]

**Comment by FestiveKyle** [comment]
Staging, production, and GKE seem to be operational.

Steps taken:
- Remove all documents from dmarcSummaries collection: 
  - `FOR dmarcSummary IN dmarcSummaries REMOVE dmarcSummary IN dmarcSummaries`
- Remove all documents fom domainsToDmarcSummaries collection:
  - `FOR domainToDmarcSummary IN domainsToDmarcSummaries REMOVE domainToDmarcSummary IN domainsToDmarcSummaries`
- Re-run DMARC summary service:
  -  `make reports`
