### ISSUE TITLE
Upgrade to Kubernetes to 1.24

### ISSUE THREAD

**Issue by h701h** [canada-ca/tracker#3745]
What is our major drive to 1.24?
- To keep pace with kubernetes releases?
- [Kubelet Credential Provider Graduates to Beta](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#major-themes)? 
- ~~Signing Release Artifacts?~~
- Istio?

- [ ] Find out options - (IMTD-Rob)
- [x] Find out if we have permissions to upgrade ourselves.

References: 
1. https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#major-themes

**Comment by CADbryon** [comment]
Latest version on Azure?
