### ISSUE TITLE
Disable TLS_CHACHA20_POLY1305_SHA256 and any other ciphers that do not comply with CCCS recommendations

### ISSUE THREAD

**Issue by h701h** [canada-ca/tracker#3765]
As per the ATO, Disable TLS_CHACHA20_POLY1305_SHA256 and any other ciphers that do not comply with CCCS recommendations.

If the use of TLS_CHACHA20_POLY1305_SHA256 is accepted. Lets close and document this here.

**Comment by sleepycat** [comment]
Recent work on Tracker has revealed that common crypto libraries are solving cipher misconfigurations by [no longer allowing people to configure ciphers when using TLS 1.3](https://go.dev/blog/tls-cipher-suites). Google's [BoringSSL](https://boringssl.googlesource.com/boringssl/+/c3b373bf4f4b2e2fba2578d1d5b5fe04e410f7cb/include/openssl/ssl.h#1470) and Go's [crypt/tls](https://pkg.go.dev/crypto/tls) implementation (part of their standard library!) are powering many projects/products, from Android to Chrome to the [Envoy proxy](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/common.proto.html?highlight=cipher_suites#extensions-transport-sockets-tls-v3-tlsparameters) that Tracker itself uses. The result is that although [our configuration specifies acceptable ciphers](https://github.com/canada-ca/tracker/blob/514dd85d6a8ba3ae7a7033bc8046dedc337b5826/app/gke/publicgateway.yaml#L32-L34), it is ignored. This leaves Tracker using a cipher (CHACHA20) that, while generally regarded as secure, has not been explicitly approved. 

Catching moments like this where the world shifts under the policy is part of why OCIO is building Tracker in the first place. We've notified the Cybercentre and are working on a resolution to feed back into policy.

**Comment by h701h** [comment]
Added to milestone 3.0 to demonstrate PoAM improvements.

**Comment by h701h** [comment]
Completed. https://github.com/canada-ca/tracker/pull/3192/files
