### ISSUE TITLE
Investigate and implement the use of session cookies as an alternative method for invalidating session identifiers than the current approach of using JSON web tokens

### ISSUE THREAD

**Issue by h701h** [canada-ca/tracker#3766]
As per the Tracker ATO, Investigate and implement the use of session cookies as an alternative method for invalidating session identifiers than the current approach of using JSON web tokens

**Comment by sleepycat** [comment]
JWTs [are mandatory](https://www.canada.ca/en/government/system/digital-government/modern-emerging-technologies/government-canada-standards-apis.html#:~:text=JSON%20Web%20Token%20(JWT)%20is%20required%20for%20RESTful%20API%20interactions.) when interacting with RESTful APIs. It's unclear why using something required by TBS policy is being flagged by TBS security. I guess this is an oversight oversight. :smile: 

Tracker was switching from an in memory JWT to cookies to allow user sessions to survive a refresh at the time of that request so this is resolved either way. Tracker and interacting with it's API may well involve JWTs in the future.
