### ISSUE TITLE
Certificate Expiry for Treasury Board Secretariat

### ISSUE THREAD

**Issue by h701h** [canada-ca/tracker#3779]
HTTPSEverywhere will phase out.
Alpha will auto renew.

Communicate to users.

Must we use TBS mandated certs?
The following certificate is set to expire on Sep 3, 2022 . 

Certificate Field	Value
Certificate Common Name	https-everywhere.canada.ca
Certificate Status	Native Cert
Certificate Type	Multi-Domain OV SSL
DN	cn=https-everywhere.canada.ca, o=Treasury Board Secretariat, l=Ottawa, st=Ontario, c=CA
Key Usage	Digital Signature, Key Encipherment
Extended Key Usage	Client and Server Authentication
Certificate Key Size	2048
Key Type	RSA
Serial Number	11697156678075934200106052815231852634
Serial Number (Hex)	8CCCA59B07396EFA892DC53D833205A
Signing Algorithm	SHA-2
Tracking ID	2365924
Certificate Friendly Name	canada.ca (Amrinder Singh)

**Subject Alternative Names	https-everywhere.canada.ca, https-partout.canada.ca, pulse.canada.ca, Suivi.canada.ca, tracker.canada.ca**

**Comment by FestiveKyle** [comment]
tracker.alpha.canada.ca didn't renew by itself. cert manager was missing an annotation for the required service account. Fixed in https://github.com/canada-ca/tracker/pull/3922
