### ISSUE TITLE
Domain Scenario Planning

### ISSUE THREAD

**Issue by lcampbell2** [canada-ca/tracker#3859]
We should have the ability to link domains that resolve to the same webpage in order to avoid redundant scanning/web checks 

- [x] Po to connect with the UK team.
- [x] [Read UK ACD one year programme](https://056gc-my.sharepoint.com/:w:/g/personal/datrudel_tbs-sct_gc_ca/EYTM5Xs7GoVGv1bqeqhheTUBXRlE1DthKA7wham8WPQ2dw?e=CxQ4VD)
- [x] https://www.ncsc.gov.uk/section/advice-guidance/all-topics?allTopics=true&topics=active%20cyber%20defence&sort=date%2Bdesc

References

1. https://developers.google.com/search/docs/advanced/crawling/consolidate-duplicate-urls#definition

**Comment by h701h** [comment]
pwgsc.gc.ca and its many alternative names.

Alternative names: pwgsc.gc.ca www.pwgsc.gc.ca www.pwgsc-tpsgc.gc.ca www.tpsgc.gc.ca www.tpsgc-pwgsc.gc.ca www.directdeposit.gc.ca pwgsc-tpsgc.gc.ca tpsgc.gc.ca tpsgc-pwgsc.gc.ca directdeposit.gc.ca spac-pspc.gc.ca depotdirect.gc.ca compensation.gc.ca remuneration.gc.ca www.spac-pspc.gc.ca www.depotdirect.gc.ca www.compensation.gc.ca www.remuneration.gc.ca

**Comment by h701h** [comment]
directdeposit.gc.ca has produces a "301 Moved Permanently"

**Comment by h701h** [comment]
different domains to support multiple device types:

https://example.com/news/koala-rampage
https://m.example.com/news/koala-rampage
https://amp.example.com/news/koala-rampage

**Comment by h701h** [comment]
server is configured to serve the same content for www/non-www http/https and protocol port variants:

http://example.com/green-dresses
https://example.com/green-dresses
http://www.example.com/green-dresses
http://example.com:80/green-dresses
https://example.com:443/green-dresses

**Comment by h701h** [comment]
http://sedsi-oliss.tpsgc-pwgsc.gc.ca/ produces 404

**Comment by h701h** [comment]
(Domain Name -> Alternative Name) -> Server (IP Address) -> Finding

IP Address -> IP Address Range -> Finding

**Comment by h701h** [comment]
Prune: Any domain that is outside of having all ASCII letters a through z (in a case-insensitive manner), the digits 0 through 9, and the hyphen-minus character ('-')
