### ISSUE TITLE
Decommission HTTPS

### ISSUE THREAD

**Issue by CADbryon** [canada-ca/tracker#3867]
- [x] IMTD https://jira.tbs-sct.gc.ca/browse/AZ-13515
- [x] Pull domain list from VM DB (CSV)  ([BACK UP LOCATION](https://056gc.sharepoint.com/sites/OCIOCyberSecurity/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=p9wNkn&xsdata=MDV8MDF8fGY4MWM0ZDZjMDVhYjRjYzRlYjUwMDhkYTdhZWExMjBmfDYzOTdkZjEwNDU5NTQwNDc5YzRmMDMzMTEyODIxNTJifDB8MHw2Mzc5NTc0NDI5NzAzMTU2MDB8R29vZHxWR1ZoYlhOVFpXTjFjbWwwZVZObGNuWnBZMlY4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaVYybHVNeklpTENKQlRpSTZJazkwYUdWeUlpd2lWMVFpT2pFeGZRPT18MXxNVGs2T1Roa1pHUmxOV1V0TVdaa1lTMDBOREUyTFdGbU9HRXRaVGMwWVRaaE5qUTVObU0wWDJNM00yWTBaamxtTFRObVl6UXROR013T1MxaE5XSXlMVFZtTkRWaU9UZzVZMlJsWWtCMWJuRXVaMkpzTG5Od1lXTmxjdz09fHw%3D&sdata=L2hqbzdLZTY1TVJraWtnR0pWbFRrZW5JM3hRYmdQU2h5bEZENmVXVjhvcz0%3D&ovuser=6397df10%2D4595%2D4047%2D9c4f%2D03311282152b%2CDATRUDEL%40tbs%2Dsct%2Egc%2Eca&OR=Teams%2DHL&CT=1660241102218&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyNy8yMjA3MDMwMDgxNSIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D&cid=d1d6e401%2Dad63%2D49fa%2Da1a1%2Dc98b8478a6f4&RootFolder=%2Fsites%2FOCIOCyberSecurity%2FShared%20Documents%2FGeneral%2F09%2E%20Cyber%20Tools%2FTracker%2Fhttps%2Deverywhere%20backups&FolderCTID=0x012000787C472D897B1B4F917F0C66116B864E))
- [ ] Communication (no one is using this service, lets avoid the work of telling everyone who is not using it; that its not there anymore.  
- [ ] Lessons Learned (low priority)

**Comment by h701h** [comment]
Ways to export the data: https://docs.microsoft.com/en-us/azure/cosmos-db/import-data

**Comment by h701h** [comment]
[BACK UP LOCATION](https://056gc.sharepoint.com/sites/OCIOCyberSecurity/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=p9wNkn&xsdata=MDV8MDF8fGY4MWM0ZDZjMDVhYjRjYzRlYjUwMDhkYTdhZWExMjBmfDYzOTdkZjEwNDU5NTQwNDc5YzRmMDMzMTEyODIxNTJifDB8MHw2Mzc5NTc0NDI5NzAzMTU2MDB8R29vZHxWR1ZoYlhOVFpXTjFjbWwwZVZObGNuWnBZMlY4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaVYybHVNeklpTENKQlRpSTZJazkwYUdWeUlpd2lWMVFpT2pFeGZRPT18MXxNVGs2T1Roa1pHUmxOV1V0TVdaa1lTMDBOREUyTFdGbU9HRXRaVGMwWVRaaE5qUTVObU0wWDJNM00yWTBaamxtTFRObVl6UXROR013T1MxaE5XSXlMVFZtTkRWaU9UZzVZMlJsWWtCMWJuRXVaMkpzTG5Od1lXTmxjdz09fHw%3D&sdata=L2hqbzdLZTY1TVJraWtnR0pWbFRrZW5JM3hRYmdQU2h5bEZENmVXVjhvcz0%3D&ovuser=6397df10%2D4595%2D4047%2D9c4f%2D03311282152b%2CDATRUDEL%40tbs%2Dsct%2Egc%2Eca&OR=Teams%2DHL&CT=1660241102218&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyNy8yMjA3MDMwMDgxNSIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D&cid=d1d6e401%2Dad63%2D49fa%2Da1a1%2Dc98b8478a6f4&RootFolder=%2Fsites%2FOCIOCyberSecurity%2FShared%20Documents%2FGeneral%2F09%2E%20Cyber%20Tools%2FTracker%2Fhttps%2Deverywhere%20backups&FolderCTID=0x012000787C472D897B1B4F917F0C66116B864E))
