### ISSUE TITLE
Preparing Web Checks/ACD meeting notes

### ISSUE THREAD

**Issue by FestiveKyle** [canada-ca/tracker#3881]
Post Meeting:

- [x] Thank you note
- [x] Place Web Check screenshots in SharePoint https://056gc.sharepoint.com/:f:/r/sites/OCIOCyberSecurity/Shared%20Documents/General/02.%20Strategy%20%26%20Design/Tracker/Gov.Uk%20Web%20Check%20screenshots?csf=1&web=1&e=YBexKq
- [x] Received screenshots
- [x] Who needs an account: Damien, Luke, Kyle, ...
- [x] Access to solution

### Topics to talk about
* Understanding how they test their scanners/results.
  * Infrastructure?
  * Regression
  * Testing when your supplies are third parties ("feed suppliers")?
* Data science pipelines to generate your reports?
* Team size over the years? Full time? Budget and recurring costs?
* Your used third party "feed suppliers"?
* Code
  * All code privately on GitHub?  
  * Can you give us read only access to some private code repos?
* Government and Industry Partnerships outside of the NSCS and the challenges of that?
  * Stats, CAFC, RCMP/NC3, CCCS/CSE,
    * Have you worked/met with any of these organizations within the context of ACD?  
* Dead ends over the years? If you could do it all again what would you do vs. not do?
* Contract clauses that trace back into your ACD?

https://056gc-my.sharepoint.com/:w:/g/personal/datrudel_tbs-sct_gc_ca/EYTM5Xs7GoVGv1bqeqhheTUBXRlE1DthKA7wham8WPQ2dw?e=CxQ4VD

**Comment by lcampbell2** [comment]
- scan schedules, the "simple" tests vs the critical vulns
- communication strategy for new 0 days, as well as inviting people onto the app

**Comment by h701h** [comment]
On 2022-09-01 Jamie H of the UK team sent us some Web Check screenshots.
