### ISSUE TITLE
User Activity Audit Logs

### ISSUE THREAD

**Issue by lcampbell2** [canada-ca/tracker#3995]
In order for better transparency of user activity, flow of domain data, and to create a more self-service model, we need to have a centralized location for super admins to view logs of user activity (adding, editing, deleting, etc.).

- [x] explore k8s logs
- [x] decide activities to log/display
- [x] create API queries for logs
- [x] create frontend page
- [x] Reason Select box
- [x] Translations
- [x] tests
- [ ] Think about how to notify all users of an org; of recent audit activity (send email update at midnight for example) (Damien put this here)

**Comment by h701h** [comment]
Add the word 'DKIM', or whatever is more appropriate to this log entry.  

![Image](https://user-images.githubusercontent.com/74711155/199779950-ed95fbbb-794b-4076-9e37-980b0c9b60a5.png)

**Comment by h701h** [comment]
When a user manually adds or removes tags this should be logged. 

- [ ] Should we do it?

![Image](https://user-images.githubusercontent.com/74711155/199781811-5dc59203-0b06-4426-bbc1-769e8b7ff6b7.png)



![Image](https://user-images.githubusercontent.com/74711155/199782016-2ccfb5c6-b1f6-4c52-b62b-cad7432049c8.png)

**Comment by h701h** [comment]
Most recent events should be shown first. 

- [ ] Should we do?

![Image](https://user-images.githubusercontent.com/74711155/199804536-bc462e88-9046-4289-bb95-93dd6e48961c.png)

**Comment by h701h** [comment]
The filters menu needs to be relocated. Its interfering with the audit log entries. Perhaps more of a horizontal look than the current vertical look. 

- [ ] Should we do?

![Image](https://user-images.githubusercontent.com/74711155/199805070-1fdabe4c-1eab-4ae2-bef2-3b8f85443ec5.png)

**Comment by h701h** [comment]
Items per page should be greater than 10. Perhaps the default is best to be 100. I'd rather scroll then paginate. 

- [ ] Should we do?


![Image](https://user-images.githubusercontent.com/74711155/199805426-84084a96-839a-483c-92fb-ba6750c4740c.png)

**Comment by h701h** [comment]
The log entry for when a user gets deleted is missing information. I deleted an account, the entry says 'update' with a blank reason. 

- [ ] Should we do?

![Image](https://user-images.githubusercontent.com/74711155/199806767-53bf5a2d-a582-4f14-b629-e9b5d085d351.png)

**Comment by h701h** [comment]
When adding a new user, the role could appear in in the 'updated property'

- [ ] Should we do?



![Image](https://user-images.githubusercontent.com/74711155/199807686-840daa74-83a3-457f-9033-972593c443e8.png)

**Comment by h701h** [comment]
While testing the create org function the tombstone data failed to load. 

- [ ] Should we do?


![Image](https://user-images.githubusercontent.com/74711155/199810761-d3dbc616-8ed8-417a-9657-7b8d03c85bd3.png)

**Comment by h701h** [comment]
"Reason" should include additional options. Not sure what else though. 

- [ ] Should we do?


![Image](https://user-images.githubusercontent.com/74711155/199810986-befc5e3e-8986-4eb7-9abc-5a762d727ae7.png)

**Comment by h701h** [comment]
"This domain no longer exists" should fail if the domain exists. 

- [ ] Should we do?

![Image](https://user-images.githubusercontent.com/74711155/199811345-3603cb9d-7540-4e5f-9f03-c0473e1ba6ae.png)

**Comment by h701h** [comment]
When adding a domain the dkim and the tag values are not being recorded. 

- [ ] Should we do?

![Image](https://user-images.githubusercontent.com/74711155/199812164-185f2563-1a39-4c2a-bb36-f6f4ea99d796.png)

**Comment by h701h** [comment]
Show record count? 

- [ ] Should we do?
- [ ] Where else can we do record counts?

**Comment by h701h** [comment]
Unable to test 'delete org' in the audit logs. See error message.



![Image](https://user-images.githubusercontent.com/74711155/199813092-5f92a8cd-b607-467e-b3d1-bb983b0fc31e.png)

**Comment by h701h** [comment]
Unable to test 'update org' in the audit logs. See error message. 



![Image](https://user-images.githubusercontent.com/74711155/199813306-4d3625a0-ee27-4d7e-9895-df5d4eb36879.png)

**Comment by h701h** [comment]
Can we reduce the size of the time stamp to yyyy-mm-dd, 24H:M. 

- [ ] Should we do it?



![Image](https://user-images.githubusercontent.com/74711155/202206189-d470cc24-d279-423f-ba16-6a180059ef8a.png)

**Comment by h701h** [comment]
When deleting an account the name of the deleted account isn't displayed correctly. 

- [ ] Should we do it?

![Image](https://user-images.githubusercontent.com/74711155/202207087-fa2ff247-e372-4bb5-a998-c16011be035b.png)

**Comment by h701h** [comment]
Remove a domain "Reason" should include additional options. "Admin error". 

 Should we do?



![Image](https://user-images.githubusercontent.com/74711155/202207687-8b46e255-d6fa-4108-8831-85f8f247f2f4.png)
