### ISSUE TITLE
Bug: I agree to all Terms, Privacy Policy & Code of Conduct Guidelines

### ISSUE THREAD

**Issue by h701h** [canada-ca/tracker#4188]
While registering an account the "I agree to all Terms, Privacy Policy & Code of Conduct Guidelines" is not clickable.

**Comment by lcampbell2** [comment]
Steps to replicate?

**Comment by h701h** [comment]
1. As an admin, create a new user account. 
2. Follow the link in the email to the following page.
3. The "I agree to all Terms, Privacy Policy & Code of Conduct Guidelines" is not clickable.
![image](https://user-images.githubusercontent.com/74711155/207948193-7a5de2a1-3ea5-4840-be18-784f8c43714c.png)
