### ISSUE TITLE
Switch to faking DNS query to send request to specific IP addresses

### ISSUE THREAD

**Issue by FestiveKyle** [canada-ca/tracker#4262]
Mock DNS resolver to set IP addresses instead of using the HostHeaderSSLAdapter.

The website https://dh480.badssl.com for example might be having issues with our current implementation. Every other client (curl, requests, sslyze) is unable to connect with error similar to "Bad DH Value". Our connection scanner is able to connect though. This might be due to how we are pinning the IP address.

**Comment by lcampbell2** [comment]
fixed in #3891
