### ISSUE TITLE
DKIM validation failing

### ISSUE THREAD

**Issue by arashmalekz** [canada-ca/tracker#4357]
Hello, 

The DKIM validation for my domain (geo.ca) is failing and I'm not sure what the issue is. This domain doesn't send emails and I've configured the the DKIM value to be "v=DKIM1; p=" which is the same as what I get when I run nslookup on tracker.canada.ca. 

Could you please advise on what the issue is? 

Thank you

**Comment by h701h** [comment]
Create an account on the Tracker platform using your organizations email address. Reach out to us at zzTBSCybers@tbs-sct.gc.ca once done. Once we affiliate you with your organization you can login to add your DKIM selector to that domain inside Tracker. This should fix the issue.

**Comment by arashmalekz** [comment]
Thank you @h701h. The issue is now resolved.
