### ISSUE TITLE
Dashboard metric: PGS HTTPS/DMARC scores

### ISSUE THREAD

**Issue by h701h** [canada-ca/tracker#4519]
Show the https/dmarc aggregated scores of only orgs where the PGS is applicable.

**Comment by lcampbell2** [comment]
Proposed Solution: 
- Unverify all non-PGS orgs
- Archive all domains belonging to unverified orgs to hide from users and future scans (keep old data)

**Comment by lcampbell2** [comment]
script was run on prod to complete the above solution. Closing issue as complete.
