### ISSUE TITLE
Not all subdomains appearing

### ISSUE THREAD

**Issue by somereality** [canada-ca/tracker#5327]
**Describe the bug**
Not all subdomains appear for pacifican.gc.ca

**To Reproduce**
1. Sign into tracker.canada.ca
2. Go to Domains
3. Search for 'pacifican'
4. Only 2 domains appear - should be a third.

**Expected behavior**
Expected to see www.pacifican.gc.ca

**Screenshots**
![image](https://github.com/canada-ca/tracker/assets/2169715/95f54d75-307f-4a02-afde-806a0de26955)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 125.0.6422.113

**Comment by lcampbell2** [comment]
Hi,

The filter shown in the screenshot above limits the domain list to only the domains claimed by your affiliated organization. If you wish to see the full unfiltered list, simply click the toggle to turn it off. If you would like to have the domain as part of your affiliated domains, you can add the domain to your organization under the admin profile or request to join the organization that has already claimed it.

Please refer all future questions about internal domain lists to the [TBS Cyber General Mailbox](mailto:zzTBSCybers@tbs-sct.gc.ca?subject=Tracker%20Issue%20Report)

Thanks,

Luke Campbell
TBS Cyber
