### ISSUE TITLE
Domains still appearing in Tracker from server that has been shut down for months

### ISSUE THREAD

**Issue by somereality** [canada-ca/tracker#5329]
Sub-domains are being listed in Tracker from a server that has been shut down since last fall (in September or October 2023).

- www2.deo.gc.ca
- www2.wd-deo.gc.ca
- www2.wd.gc.ca
- www2dev.deo.gc.ca
- www2dev.wd-deo.gc.ca
- www2dev.wd.gc.ca

The web status for all is listed as informational, and all have the same email status - but didn't expect to see any of these domains listed at all.

**Comment by lcampbell2** [comment]
Hi,

The domains listed above are required to be in Tracker as they still have DNS records. This requires them to be scanned for DMARC, SPF, and DKIM compliance to the [Email Management Services Configuration Requirements](https://www.canada.ca/en/government/system/digital-government/policies-standards/enterprise-it-service-common-configurations/email.html). The domains will be automatically removed once they return an rcode of "NXDOMAIN".

Please refer all future questions about internal domain lists to the [TBS Cyber General Mailbox](mailto:zzTBSCybers@tbs-sct.gc.ca?subject=Tracker%20Issue%20Report)

Thanks,

Luke Campbell
TBS Cyber
