### ISSUE TITLE
Create custom Spilo image for PGO

### ISSUE THREAD

**Issue by tparrott-cse** [canada-ca/tracker#537]
docker_image Spilo Docker image for Postgres instances. For production, don't rely on the default image, as it might be not the most up-to-date one. Instead, build your own Spilo image from the github repository.

https://github.com/zalando/spilo

**Comment by nslandolt** [comment]
I've put the latest image that I built and that I tested with the API that seems to be working as far as I can tell. It can be found in the gcp container registry siplo directory.
